package gopenflow

const (
	STRATOS_EXPERIMENTER_ID = 0xFF00E04D
)

const (
	STRATOS_OXM_FIELD_BASIC = iota
	STRATOS_OXM_FIELD_RADIOTAP
)

const (
	STROXM_BASIC_UNKNOWN = iota
	// match, oob, set
	STROXM_BASIC_DOT11
	// match, set
	STROXM_BASIC_DOT11_FRAME_CTRL
	STROXM_BASIC_DOT11_BSSID
	STROXM_BASIC_DOT11_TAG
	STROXM_BASIC_DOT11_SSID
	// match
	STROXM_BASIC_DOT11_MGMT_CAPTURE_PORT
	STROXM_BASIC_DOT11_BEACON_CAPTURE_PORT
)

const (
	STROXM_RADIOTAP_TSFT = iota
	STROXM_RADIOTAP_FLAGS
	STROXM_RADIOTAP_RATE
	STROXM_RADIOTAP_CHANNEL
	STROXM_RADIOTAP_FHSS
	STROXM_RADIOTAP_DBM_ANTSIGNAL
	STROXM_RADIOTAP_DBM_ANTNOISE
	STROXM_RADIOTAP_LOCK_QUALITY
	STROXM_RADIOTAP_TX_ATTENUATION
	STROXM_RADIOTAP_DB_TX_ATTENUATION
	STROXM_RADIOTAP_DBM_TX_POWER
	STROXM_RADIOTAP_ANTENNA
	STROXM_RADIOTAP_DB_ANTSIGNAL
	STROXM_RADIOTAP_DB_ANTNOISE
	STROXM_RADIOTAP_RX_FLAGS
	STROXM_RADIOTAP_TX_FLAGS
	STROXM_RADIOTAP_RTS_RETRIES
	STROXM_RADIOTAP_DATA_RETRIES
	_
	STROXM_RADIOTAP_MCS
	STROXM_RADIOTAP_AMPDU_STATUS
)

type MgmtFramePrefix []byte

// NL80211_ATTR_FRAME_MATCH
type MgmtFrameAdd MgmtFramePrefix
type MgmtFrameRemove MgmtFramePrefix
